### ISSUE TITLE
Tinkerforge sensors

### ISSUE THREAD

**Issue by kylerlaird** [kylerlaird/tractobots#6]
What is the best way to incorporate the [Tinkerforge sensors](https://github.com/gus484/ros-tinkerforge_sensors)?

**Comment by solosito** [comment]
How to incorporate? What exactly you mean? Just modifying the bringup launch file should be enough in case you just want to launch it together with the rest.

**Comment by solosito** [comment]
Added. Now you should be able to launch it.

**Comment by kylerlaird** [comment]
I didn't find a .deb for the Tinkerforge sensors so I added it to the source tree and launch file (same as you did).  It seems to work.

I now get lots of these messages:
[ INFO] [1493646720.882067951]: Initial odometry pose is Origin: (0 0 0)
Rotation (RPY): (0, -0, 0)
